# Generated by Django 3.0.1 on 2020-02-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_about_announcements_chairman_counsellor_faq_gallery_psychiatrist'),
    ]

    operations = [
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
