# Generated by Django 3.0.1 on 2020-02-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='counsellor_timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timings', models.TextField(null=True)),
            ],
        ),
    ]
